name: MyAdmins
version: '1.0-SNAPSHOT'
main: me.aviloo.myAdmins.MyAdmins
api-version: '1.19'
authors: [ Aviloo ]
commands:
  kick:
    usage: </command>
  ban:
    usage: </command>
  banip:
    usage: </command>
  tempban:
    usage: </command> ник, время(20s,20m,20h,20d), причина
  myadmin:
    usage: </command>
    aliases:
      - mya
  getpunish:
    usage: </command>
  ac:
    usage: </command>
  report:
    usage: </command>
    aliases:
      - rep
  reports:
    usage: </command>
  vanish:
    usage: </command>
    aliases:
      - v
