server_name: "[+]"
link: "vk.com/orumii"
message_dont_have_perm: "You don`t have permissions to do this"
show_shorts: "true"
Strings:
  - "- Добавлен Боевой Пропуск"
  - "- Добавленны Ларцы "
  - "- Изменены Квесты"
  - "- Исправлены баги"
  - "- Устранены лаги"
