name: MyTraderReloaded
version: '${project.version}'
main: com.aviloo.mytraderreloaded.MyTraderReloaded
api-version: 1.19
authors: [ Aviloo ]
description: add Trader to your server
softdepend: [Vault, PlayerPoints, Essentials]
depend: [PlaceholderAPI]
commands:
  secretsellercommand:
    usage: /<command>
    description: command for players. Use by NPC
  seller:
    usage: /<command>
    description: команда для донатеров. Использовать можно где угодно
  sellertype:
    usage: /<command> reload
    description: команда позволяет перезагружать тип скупщика.
  secretdonatshopcommand:
    usage: /<command>
    description: команда позволяет открыть меню донат магазина
  mytrader:
    usage: /<command>
    description: позволяет перезагружать конфиг плагина.
  traderreputation:
    usage: /<command> take|set|add|reset {Ник Игрока} {кол-во очков}
  sellersettype:
    usage: /<command> тип_скупщика
  expansionstestcommand:
    description: Тестовая команда для отладки заполнителей
    usage: /<command>
  newseller:
    description: Тестовое меню
    usage: /<command>
permissions:
  mytrader.seller:
    description: позволяет использовать комманду /seller
