name: MyTraderReloaded
version: '${project.version}'
main: com.aviloo.mytraderreloaded.MyTraderReloaded
api-version: 1.19
authors: [ Aviloo ]
description: Плагин на скупщика
softdepend: [Vault, PlayerPoints, Essentials]
depend: [PlaceholderAPI]
commands:
  mytrader:
    usage: /<command>
  seller:
    usage: /<command>
    description: команда для донатеров. Использовать можно где угодно
permissions:
  mytrader.seller:
    description: позволяет использовать команду /seller
