name: MyCrafts
version: '1.0-SNAPSHOT'
main: me.aviloo.mycrafts.MyCrafts
api-version: '1.19'
depend: [WorldEdit, Vault, PlaceholderAPI]
commands:
  mycrafts:
    usage: /<command>
  uc:
    usage: /<command>
permissions:
  mycrafts.chancex2:
    description: Добавляет x2 шанс на успешный крафт.