name: MyScoreboard
version: '${project.version}'
main: com.aviloo.myscoreboard.MyScoreboard
api-version: 1.19
softdepend: [Vault, PlayerPoints, LuckPerms, PlaceholderAPI, Essentials]
authors: [ Aviloo ]
commands:
  myscoreboard:
    usage: /<command>
    description: allow customize you own scoreboard.
    aliases:
      - mysb
  seteventboard:
    usage: /<command> [EventType]
